"""empty message

Revision ID: 0200705e8a05
Revises: 
Create Date: 2017-12-23 15:44:38.645380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0200705e8a05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('a', sa.String(length=100), nullable=True),
    sa.Column('b', sa.String(length=100), nullable=True),
    sa.Column('c', sa.String(length=100), nullable=True),
    sa.Column('d', sa.String(length=100), nullable=True),
    sa.Column('rightAnswer', sa.String(length=1), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    # ### end Alembic commands ###
