"""empty message

Revision ID: 40577a3d2dd6
Revises: 
Create Date: 2018-01-07 13:52:02.015216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40577a3d2dd6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=35), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(length=35), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('category', sa.String(length=25), nullable=True),
    sa.Column('cost', sa.Numeric(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['users.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_table('users')
    # ### end Alembic commands ###
